# Imagen base
FROM python:3.12-slim

# Actualizacion de ubuntu e instalacion de paquetes
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl

# Instalacion del CLI de GCP (https://cloud.google.com/sdk/docs/install?hl=es-419#deb)
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN apt-get update && apt-get install -y git vim net-tools build-essential google-cloud-cli=473.0.0-0

# Me dirijo al workspace (cd /ws/code) 
WORKDIR /ws/code

# Variable de entorno
ENV PYTHONPATH=/ws/code/src